name: Build Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Application
        run: |
          go build -o build/ucli main.go

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ucli
          path: build/ucli
